site_name: Mojang

theme:
    name: readthedocs

extra_css:
  - css/extra.css

nav:
    - Installation:
      - 'Getting Started': 'index.md'
      - 'Reference': 'reference.md'

    - MOJANGAPI:
      - 'API Methods': 'api.md'

    - META:
        - 'License': 'license.md'
        - 'Legal': 'legal.md'
